string id           #unique speaker id
float32[] embedding #Speaker embedding, leave empty for last embedding
# Usefull when you used the action and the person is unkown (high cosine dist)

---

bool success
string message