services:
  vosk_ros2:
    container_name: vosk_ros2
    image: vosk_ros2
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      ROS_DOMAIN_ID: 42
      DISPLAY: $DISPLAY
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    volumes:
      - /dev/snd:/dev/snd
      - ../vosk_ros2:/root/ros2_ws/src/vosk_ros2
      - ../speakers:/speakers
    command: ros2 run vosk_ros2 vosk_ros2_node

