# Goal

bool continuous         # If true, keep listening continuously until canceled
bool publish_partial    # If true, send partial results as feedback
string wave_file        # Path to store the audio file, if empty, don't save
# In continuous a counter is added to the file name starting with _0.wav
---
# Result

RecognizedSpeech final_result  # The final recognized speech, will be empty in continuous mode
bool success                   # True if recognition succeeded
string message                 # Reason if recognition failed

---
# Feedback

RecognizedSpeech continuous_result # Like final_result, just for continuous mode
string partial_text                # Simple partial text during recognition